### ISSUE TITLE
BD71815AGW PMIC driver upstream?

### ISSUE THREAD

**Issue by rostokus** [RohmSemiconductor/Linux-Kernel-PMIC-Drivers#1]
Guys, any plans for upstreaming BD71815AGW PMIC driver?

**Comment by M-Vaittinen** [comment]
> Guys, any plans for upstreaming BD71815AGW PMIC driver?

I have been thinking of that. I haven't started any actions as I am unsure if upstream kernels are used with systems having this PMIC. It kind of makes no sense to add code to be maintained at upstream if no one uses it :) Besides, at the current state of this driver - it would require quite a bit of polishing (and testing after this) before it would be in a shape to be added to upstream. But I will sure consider this if I find upstream users for this PMIC.

Did you have some specific HW-setup / project in mind which could benefit from this being upstream?

**Comment by rostokus** [comment]
Yes, we are using this chip in our product. Previously we used older version of BD71815 driver for 4.1.X kernel and now migrating to newer version which requires manual updates of BD71815 driver. Would be great if this driver is upstreamed so that upgrade process was more straightforward.

By the way, what is the expected way to update BD71815 driver for using custom batteries? For example, have you considered making bd7181x-power.c more generic and move all battery specific stuff (voltage, levels, current, etc.) to separate custom vendor files? This would make the process of adding new battery support much easier

**Comment by M-Vaittinen** [comment]
I am now walking on a thin ice as I am not an expert on this driver. Nor do I have a long background on power-supply framework...

But my 10 cents on this topic is:

1. There has not been any active development on this driver (as far as I know).

2. As I said, I have thought of upstreaming this - but never proceed with it. If I started today it would probably take few months untill this was in-tree upstream. Biggest issue I see here is the state of charge computation - which should probably be dropped from this driver. It really makes no sense to implement same state-of-charge computation in each driver written for a device containing coulomb counter. This driver should have methods to get the states/coulomb counter values, OCV values and rest of the device specific stuff - but the actual computation should be handled by a generic SW entity sitting on top of these type of drivers. Learning and doing all of this would require a while from me. I won't say I will not start a task like this - but I do say that even if I start - it will take some time before anything is available :)

3. What comes to expected way of supporting other batteries - I don't have the answer right now. As I said, I do not know the history of this driver. After a quick look it seems to me this driver contains battery specific stuff hard-coded and has really been designed for a specific battery only. Just as a pointer - the BD71828 PMIC's not upstreamed charger driver has probably a common ancestor with this driver. (I see similarities). There module parameters were used to allow userland to override the battery specific parameters. Maybe you could try modifying this driver to also support it. Actually, I have also played with a thought of reworking and upstreaming the charger driver for bd71828 (there I have same question about users of in-tree drivers) and while I thought of it I also noted that some systems bring for example the OCV tables from device-tree. That might also be an option to bring in some battery data. Unfortunately the DT approach (as well as this hard-coding) may cause problems if battery is changed without modifying the DT/driver. I think some setups do some type of battery probing at boot time. But as I said - I don't have the experience to tell what should be the best approach. Oh - in case you wish to see the battery parameter approach - here's a link to the not upstreamed bd71828 / bd71827 charger driver:
https://github.com/M-Vaittinen/linux/blob/bd71828-v5.3-rc4-dev/drivers/power/supply/bd71827-power.c

**Comment by KokiOkada-Rohm** [comment]
Hi @rostokus 
Thanks for having been using our chip. Since it can take much time to fulfil your request, can you fill information in https://www.rohm.com/contactus to issue a formal request to us?

**Comment by rostokus** [comment]
@KokiOkada-Rohm I think I can do this. Actually it is not a blocker for us now as we can hard-code our battery specific parameters, but in general having kernel driver upstreamed will simplify kernel upgrade. That's why I have brought this up as probably we are not the only customer that will benefit from this

**Comment by M-Vaittinen** [comment]
Hello @rostokus,

I have bad news. I actually started drafting the modified power-supply driver which could push some of the logic from PMIC driver to the power-supply framework. I did plan sending an RFC to community to see what PM folks think of that approach - but...
...Today I learned that part of the fuel-gauging algorithm presented in the driver may be patented by ROHM. I don't want to add code which implements patented procedure to upstream unless I get some legal Ok. to do that. It would be like asking for a nose-bleed to first work to get some code upstreamed only to find that the other side of company is later preventing the use on other ICs... So, I will suspend my upstreaming activities untill I know what is the take of legal side of business :/

Meanwhile, I further learned that the procedure for getting the battery parameters is not public information. (And I don't personally even know this procedure). So I unfortunately I must ask you to contact the support also for getting the parameters for the new type of battery. I have heard our FAEs are top notch though ;) So I hope you will get quick support!

**Comment by M-Vaittinen** [comment]
Just wanted to let you know that after some ROHM internal discussions I am resuming the drafting of fuel gauge driver as a "background task". Not sure how it will work out though.

**Comment by M-Vaittinen** [comment]
As a update.

I did first initial attempt to pull the fuel-gauging logic out of the driver and to add it in the Linux power-supply core. Sent a RFC (request for comments) to the Linux kernel community power-management people to get some early feedback about this. Let's see if there is any interest.

https://lore.kernel.org/linux-pm/cover.1606384967.git.matti.vaittinen@fi.rohmeurope.com/t/#u

So no promises and the BD71815 or BD71828 driver(s) have not been converted to use this new code presented in RFC - and this RFC has not been tested or finalized - it really is just that - an RFC.

**Comment by M-Vaittinen** [comment]
Hello @rostokus 

I have continued drafting this change using the BD71828 driver (because I know BD71828 better than BD71815). I think I am slowly making some progress.

I wonder if you are willing/able to do testing using BD71815 on a real device if I do try converting BD71815 charger-driver to use the new fuel-gauge logic?

**Comment by M-Vaittinen** [comment]
For anyone interested - here is a highly unstable development branch where this work can be followed. Please note that this branch is _really_ unstable and untested. It is rebased without warning and commits have not been tested. I may even push unfinished, not compiling changes there in order to not lose changes if HDD breaks. So you should not take SW from this branch - but you can watch/comment the changes / give suggestions etc :)

https://github.com/M-Vaittinen/linux/commits/swgauge-dev

**Comment by rspolyak** [comment]
Hi Matti, sorry for delayed reply. Thanks for keeping me updated.
Our current driver for BD71815 works fine, so I have moved forward to other tasks.
However, it would be really useful to have BD71815 driver up streamed so that we use it instead of custom one.

To answer your question, yes, I can test your latest efforts for BD71815 driver on real hardware. There might be some delay from my side as there is still some linux bring up to be done, but I can test once you are ready.

Thanks for keep working on this!

**Comment by M-Vaittinen** [comment]
Upstreaming effort has been started. Please note that the charger driver is not included in this set of patches:
https://lore.kernel.org/lkml/cover.1610110144.git.matti.vaittinen@fi.rohmeurope.com/

**Comment by M-Vaittinen** [comment]
version 2. Power-supply driver is still not included.
https://lore.kernel.org/lkml/cover.1611037866.git.matti.vaittinen@fi.rohmeurope.com/T/#t

**Comment by M-Vaittinen** [comment]
BD71815 support is getting upstream. The power-supply part is currently not included upstream. (See information about experimental power-supply driver work from https://github.com/RohmSemiconductor/Linux-Kernel-PMIC-Drivers/tree/master/BD71815)

At the moment the BD71815 upstream patches (except the power-supply) are in MFD-next tree. They are eventually expected to land to Linux v5.13 or v5.14. Meanwhile curious minds can take a peek at MFD-tree:
https://git.kernel.org/pub/scm/linux/kernel/git/lee/mfd.git/log/?h=for-mfd-next
